[FEAT] Changed id type to Union{Int, String}
DeloitteOptimalReality/LightOSM.jl pull request #101
Opened 2024-03-06 22:48 UTC by AzilAverakot

Added functionality to handle String ids.

2024-03-06 23:19 UTC, captchanjack commented on Project.toml
> +version = "0.2.13"
```suggestion
version = "0.3.0"
```

2024-03-06 23:20 UTC, captchanjack commented on src/constants.jl
> +const DEFAULT_OSM_INDEX_TYPE = Int64
```suggestion
const DEFAULT_OSM_INDEX_TYPE = Int32
```

2024-03-06 23:21 UTC, captchanjack commented on src/graph_utilities.jl
>  node_id_to_index(g::OSMGraph, x::Integer) = g.node_to_index[x]
```suggestion
node_id_to_index(g::OSMGraph, x::T <: Union{Int, String}) = g.node_to_index[x]
```

2024-03-06 23:21 UTC, captchanjack commented on src/graph_utilities.jl
> +node_id_to_index(g::OSMGraph, x::Vector{<:String}) = [node_id_to_index(g, i) for i in x]
won't need this if `x` is typed parametrically

2024-03-06 23:22 UTC, captchanjack commented on src/graph_utilities.jl
> +index_to_dijkstra_state(g::OSMGraph, x::String) = g.dijkstra_states[x]
same here

2024-03-06 23:22 UTC, captchanjack commented on src/graph_utilities.jl
> +    node_id_to_dijkstra_state(g::OSMGraph, x::String)
same here

2024-03-06 23:22 UTC, captchanjack commented on src/graph_utilities.jl
> +set_dijkstra_state_with_index!(g::OSMGraph, index::String, state) = push!(g.dijkstra_states, index, state)
same here

2024-03-06 23:22 UTC, captchanjack commented on src/graph_utilities.jl
> +set_dijkstra_state_with_node_id!(g::OSMGraph, node_id::String, state) = push!(g.dijkstra_states, node_id_to_index(g, node_id), state)
same here

2024-03-06 23:22 UTC, captchanjack commented on src/graph_utilities.jl
> +maxspeed_from_node_id(g, x::String) = g.nodes[x].tags["maxspeed"]
same here

2024-03-06 23:23 UTC, captchanjack commented on src/nearest_node.jl
>  nearest_node(g::OSMGraph, node_id::Integer) = nearest_node(g, g.nodes[node_id])
same here


```suggestion
nearest_node(g::OSMGraph, node_id::T <: Union{..,..}) = nearest_node(g, node_to_index(g, node_id))
```

2024-03-06 23:24 UTC, captchanjack commented on src/nearest_node.jl
> +function nearest_node(g::OSMGraph, node_ids::AbstractVector{<:String})
same here

2024-03-06 23:24 UTC, captchanjack commented on src/nearest_way.jl
> +function nearest_point_on_way(g::OSMGraph, point::GeoLocation, way_id::String)
same here

2024-03-13 09:00 UTC, captchanjack commented on src/graph.jl
> +    # if precompute_dijkstra_states
did you make a change here?

2024-03-13 23:23 UTC, captchanjack requested changes

2024-03-13 23:30 UTC, AzilAverakot commented on src/types.jl
> +`T<:String`
Can't set a type to a constant for types.jl since Julia doesn't allow this.

2024-03-14 03:24 UTC, captchanjack commented
Lgtm

2024-03-14 03:25 UTC, merged